name: test-github-actions
run-name: ${{ github.actor }} checking Github Actions
on: [push]
jobs:
  deploy:
    name: Upload result to Amazon S3
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Configure AWS credentials from Account
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::578120814996:role/GithubActionsRole
          aws-region: eu-west-1
      - name: List S3 buckets
        run: |
          aws s3 ls s3://project-cloudformation-sessions/
      - name: run crawler
        env:
        EMAIL_HOST: ${{ EMAIL_HOST }}
        EMAIL_ID: ${{ EMAIL_ID }}
        EMAIL_PASSWORD: ${{ EMAIL_PASSWORD }}
        run: |
          type -a python3
          export EMAIL_HOST="$EMAIL_HOST"
          export EMAIL_ID="$EMAIL_ID"
          export EMAIL_ID="$EMAIL_ID"
          echo ${{ EMAIL_HOST }}
          /usr/bin/python3 -m pip install -r requirements.txt
          cd ./src/selenium_crawlers
          /usr/bin/python3 ./indeed_selenium.py
