name: test-github-actions
run-name: ${{ github.actor }} Github Actions
on:
#  push:
  pull_request:
    branches:
      - master
  schedule:
    - cron:  '*/5 * * * *'
jobs:
  deploy:
    name: Run Web Crawlers
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          {ref: workflow-schedule-test}
      - name: Configure AWS credentials from Account
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::578120814996:role/GithubActionsRole
          aws-region: eu-west-1
      - name: List S3 buckets
        run: |
          aws s3 ls s3://project-cloudformation-sessions/
      - name: run crawler
        env:
          EMAIL_HOST: ${{ secrets.EMAIL_HOST }}
          EMAIL_ID: ${{ secrets.EMAIL_ID }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
        run: |
          type -a python3
          echo $EMAIL_HOST
          /usr/bin/python3 -m pip install -r requirements.txt
          cd ./src/selenium_crawlers
          /usr/bin/python3 ./indeed_selenium.py

# https://crontab.guru/examples.html
# https://www.jeffgeerling.com/blog/2020/running-github-actions-workflow-on-schedule-and-other-events